
package ttu.idu0080.ee.order.service.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:57:10.590+03:00
 * Generated source version: 2.7.18
 * 
 */
public final class OrderWebService_OrderServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.order.ee.idu0080.ttu/", "OrderServiceService");

    public OrderWebService_OrderServicePort_Client() {
    }
    
    public Order getOrderById(int orderId) {
    	URL wsdlURL = OrderServiceService.WSDL_LOCATION;
    	String args[] = {""};
    	Order order = new Order();
    	
    	if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    // wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
    	
    	OrderServiceService ss = new OrderServiceService(wsdlURL, SERVICE_NAME);
        OrderWebService port = ss.getOrderServicePort();
        
        order = port.getOrderById(orderId);
    	
    	return order;
    }

}
