
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.ee.order.service.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:57:10.627+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://service.order.ee.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/KT4_services/services/OrderServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.ee.order.service.client.OrderWebService")
                      
public class OrderWebServiceImpl implements OrderWebService {

    private static final Logger LOG = Logger.getLogger(OrderWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.ee.order.service.client.OrderWebService#getOrderById(int  arg0 )*
     */
    public ttu.idu0080.ee.order.service.client.Order getOrderById(int arg0) { 
        LOG.info("Executing operation getOrderById");
        System.out.println(arg0);
        try {
            ttu.idu0080.ee.order.service.client.Order _return = new ttu.idu0080.ee.order.service.client.Order();
            ttu.idu0080.ee.order.service.client.Customer _returnCustomer = new ttu.idu0080.ee.order.service.client.Customer();
            _returnCustomer.setCustomerId(1060635251);
            _returnCustomer.setFirstName("FirstName1365130900");
            _returnCustomer.setLastName("LastName-1336170367");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(-935906559);
            _return.setPriceTotal(0.7832456f);
            ttu.idu0080.ee.order.service.client.Seller _returnSeller = new ttu.idu0080.ee.order.service.client.Seller();
            java.util.List<ttu.idu0080.ee.order.service.client.Address> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.ee.order.service.client.Address>();
            ttu.idu0080.ee.order.service.client.Address _returnSellerAddressesVal1 = new ttu.idu0080.ee.order.service.client.Address();
            _returnSellerAddressesVal1.setCountry("Country1525381820");
            _returnSellerAddressesVal1.setCounty("County-480771764");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setSellerId(-1421673649);
            _returnSeller.setSellerName("SellerName-515088962");
            _return.setSeller(_returnSeller);
            ttu.idu0080.ee.order.service.client.Address _returnShippingAddress = new ttu.idu0080.ee.order.service.client.Address();
            _returnShippingAddress.setCountry("Country699972342");
            _returnShippingAddress.setCounty("County1260413129");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
