package ttu.idu0080.ee.order.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:57:10.637+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.order.ee.idu0080.ttu/", name = "OrderWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://service.order.ee.idu0080.ttu/", className = "ttu.idu0080.ee.order.service.client.GetOrderById")
    @WebMethod(action = "urn:GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://service.order.ee.idu0080.ttu/", className = "ttu.idu0080.ee.order.service.client.GetOrderByIdResponse")
    public ttu.idu0080.ee.order.service.client.Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
