package ttu.idu0080.ee.offer.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:58:43.320+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.offer.ee.idu0080.ttu/", name = "IOfferService")
@XmlSeeAlso({ObjectFactory.class})
public interface IOfferService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTransportOffer", targetNamespace = "http://service.offer.ee.idu0080.ttu/", className = "ttu.idu0080.ee.offer.service.client.GetTransportOffer")
    @WebMethod
    @ResponseWrapper(localName = "getTransportOfferResponse", targetNamespace = "http://service.offer.ee.idu0080.ttu/", className = "ttu.idu0080.ee.offer.service.client.GetTransportOfferResponse")
    public ttu.idu0080.ee.offer.service.client.TransportOffer getTransportOffer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ttu.idu0080.ee.offer.service.client.Order arg1
    );
}
