
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.ee.offer.service.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:58:43.310+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "OfferServiceService",
                      portName = "OfferServicePort",
                      targetNamespace = "http://service.offer.ee.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/KT4_services/services/OfferServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.ee.offer.service.client.IOfferService")
                      
public class IOfferServiceImpl implements IOfferService {

    private static final Logger LOG = Logger.getLogger(IOfferServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.ee.offer.service.client.IOfferService#getTransportOffer(int  arg0 ,)ttu.idu0080.ee.offer.service.client.Order  arg1 )*
     */
    public ttu.idu0080.ee.offer.service.client.TransportOffer getTransportOffer(int arg0,ttu.idu0080.ee.offer.service.client.Order arg1) { 
    	LOG.info("Executing operation getTransportOffer");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            ttu.idu0080.ee.offer.service.client.TransportOffer _return = new ttu.idu0080.ee.offer.service.client.TransportOffer();
            _return.setDeliveryDate(new java.math.BigInteger("-88967300155970963751265635078644123475"));
            _return.setOfferId("OfferId1906017976");
            _return.setTransportPrice(0.5956291f);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
