
package ttu.idu0080.ee.order.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat May 27 12:52:49 EEST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getOrderById", namespace = "http://service.order.ee.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrderById", namespace = "http://service.order.ee.idu0080.ttu/")

public class GetOrderById {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

