
package ttu.idu0080.ee.order.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat May 27 12:52:49 EEST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getOrderByIdResponse", namespace = "http://service.order.ee.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrderByIdResponse", namespace = "http://service.order.ee.idu0080.ttu/")

public class GetOrderByIdResponse {

    @XmlElement(name = "return")
    private ttu.idu0080.ee.order.Order _return;

    public ttu.idu0080.ee.order.Order getReturn() {
        return this._return;
    }

    public void setReturn(ttu.idu0080.ee.order.Order new_return)  {
        this._return = new_return;
    }

}

