
package ttu.idu0080.ee.offer.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:46:20.726+03:00
 * Generated source version: 2.7.18
 * 
 */
 
public class IOfferServiceServer{

    protected IOfferServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ttu.idu0080.ee.offer.service.OfferService();
        String address = "http://localhost:9090/OfferServicePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new IOfferServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 