
package ttu.idu0080.ee.courier.service.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:58:09.169+03:00
 * Generated source version: 2.7.18
 * 
 */
public final class CourierWebService_CourierServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.courier.ee.idu0080.ttu/", "CourierServiceService");

    public CourierWebService_CourierServicePort_Client() {
    }
    
    public List<Courier> getAllCouriers() {
    	URL wsdlURL = CourierServiceService.WSDL_LOCATION;
    	String args[] = {""};
    	List<Courier> couriers = new ArrayList<Courier>();
    	
    	if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    // wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
    	
    	CourierServiceService ss = new CourierServiceService(wsdlURL, SERVICE_NAME);
        CourierWebService port = ss.getCourierServicePort();
        
        couriers = port.getAllCouriers();
    	
    	return couriers;
  	
    }
    
    public Courier getCourierById(int courierId) {
    	URL wsdlURL = CourierServiceService.WSDL_LOCATION;
    	String args[] = {""};
    	Courier courier = new Courier();
    	
    	if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    // wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
    	
    	CourierServiceService ss = new CourierServiceService(wsdlURL, SERVICE_NAME);
        CourierWebService port = ss.getCourierServicePort();
        
        courier = port.getCourierById(courierId);
    	
    	return courier;
    }

}
