package ttu.idu0080.ee.courier.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-28T12:58:09.213+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.courier.ee.idu0080.ttu/", name = "CourierWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface CourierWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCouriers", targetNamespace = "http://service.courier.ee.idu0080.ttu/", className = "ttu.idu0080.ee.courier.service.client.GetAllCouriers")
    @WebMethod(action = "urn:GetAllCouriers")
    @ResponseWrapper(localName = "getAllCouriersResponse", targetNamespace = "http://service.courier.ee.idu0080.ttu/", className = "ttu.idu0080.ee.courier.service.client.GetAllCouriersResponse")
    public java.util.List<ttu.idu0080.ee.courier.service.client.Courier> getAllCouriers();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCourierById", targetNamespace = "http://service.courier.ee.idu0080.ttu/", className = "ttu.idu0080.ee.courier.service.client.GetCourierById")
    @WebMethod(action = "urn:GetCourierById")
    @ResponseWrapper(localName = "getCourierByIdResponse", targetNamespace = "http://service.courier.ee.idu0080.ttu/", className = "ttu.idu0080.ee.courier.service.client.GetCourierByIdResponse")
    public ttu.idu0080.ee.courier.service.client.Courier getCourierById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
