
package ttu.idu0080.ee.courier.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat May 27 13:00:23 EEST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllCouriers", namespace = "http://service.courier.ee.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllCouriers", namespace = "http://service.courier.ee.idu0080.ttu/")

public class GetAllCouriers {


}

